### ISSUE TITLE
[Competition Bug]: swap tokens from btsg to delta9 recording (D9) but swapped tokens don't appear in assets

### ISSUE THREAD

**Issue by SecretivePloter** [bitsongofficial/sinfonia-ui#273]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

when I want to do a swap on the swap page https://testnet.sinfonia.zone/swap?from=BTSG&to=D9, I enter a number of tokens to be exchanged for D9, it can be seen that the transaction went smoothly and is recorded in the transaction history.
but the problem is that I can't use the D9 token that I just swapped to put in the liquidity pool, my D9 token also doesn't appear on the assets page https://testnet.sinfonia.zone/assets

### Describe the issue behavior

swapped tokens can't be put into the liquidty pool and aren't recorded in assets even though they can still be seen in the transaction history section, I'm afraid this bug will have a big impact on users

### BitSong Public Address

bitsong1mud034pkm38y4m5dextd9fvm4a22duj6ahmsv3

### Osmosis Public Address

osmo1la6flsm8nh72jtm4y4rnnq6p35zqe4t9ufstxr

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54 

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
D9 tokens are in your wallet:

```yaml=
balances:
- amount: "1607879"
  denom: ibc/46002E7A0CC76317EFE8BAD0F113147CDD60464A10797B2BBD79F900B7626106
- amount: "2175098136"
  denom: ibc/8B066EED78CCC6A90E963C81EB4B527C28FE538BE396B8756F4C4BFC53C74221
- amount: "106716"
  denom: ibc/A7FEA25683CED4D27219CFF6C024E108F5DEFA1E48B039A60B7C18B1C34F2FBC
- amount: "42670"
  denom: ibc/E24BFA26F417771E855676A7916741D0E72AE3E782A4C002DF935DF0DC38EC2B
pagination:
  next_key: null
  total: "0"
```

**ibc/A7FEA25683CED4D27219CFF6C024E108F5DEFA1E48B039A60B7C18B1C34F2FBC** is the IBC denom for **D9**
